### ISSUE TITLE
Strange icon behavior

### ISSUE THREAD

**Issue by faveoled** [flathub/io.gitlab.jazztickets.openflap#1]
I'm on Ubuntu 22.04.1.
When opening the app its icon doesn't appear in the opened apps icons on the left panel.
Only switching to a different app makes it appear there.
The way app opens look strange: first black window appears just to be closed and a new one created within the same second

**Comment by jazztickets** [comment]
I added a SDL_SetWindowIcon call so maybe that'll fix it.

**Comment by faveoled** [comment]
1.0.6r76 icon appears on the first run but not on later runs. App window still flickers when opening

**Comment by jazztickets** [comment]
Probably just a bug with Ubuntu's panel. Try pinning it, or using the window list extension. I don't see how this is related to openflap. It works fine on other distros/DEs.

**Comment by faveoled** [comment]
Pinning works. openflap is the only app that has such problems
